server:
  address: 0.0.0.0
  port: 9119
  metrics_port: 9120
  max_connections: 5000
chains:
  "160010":
    endpoint: http://localhost:32002
    eth_send_raw_delegates:
      - http://127.0.0.1:32005
    signers:
      num_signers: 1
    assets:
      ethereum:
        address: "0x0000000000000000000000000000000000000000"
        fee_token: true
        interop: false
quote:
  constantRate: 1
  gas:
    intentBuffer: 100000
    txBuffer: 100000
  ttl: 604800
  rateTtl: 300
transactions:
  num_signers: 1
  max_pending_transactions: 100
  max_transactions_per_signer: 16
  max_queued_per_eoa: 1
  balance_check_interval: 5
  nonce_check_interval: 60
  transaction_timeout: 60
  public_node_endpoints:
    "160010": http://localhost:32002
  priority_fee_percentile: 20
orchestrator: "0x6db20c530b3f96cd5ef64da2b1b931cb8f264009"
legacy_orchestrators: []
legacy_delegation_proxies: []
delegation_proxy: "0xdec3326be4badb9a1fa7be473ef8370da775889a"
simulator: "0x70e9f1967498e8d863b371d0d6b22da6b53e8d05"
funder: "0xcc97bb833f9d361fd8f65e02ba4b8413e1e0ae0d"
escrow: "0xbfff570853d97636b78ebf262af953308924d3d8"
fee_recipient: "0x0000000000000000000000000000000000000000"
database_url: null
log_level: debug
log_format: json
